title: <p align="center"> Indrik Wijaya </p>

logo: "/images/grad_photo.jpeg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://linkedin.com/in/indrik-wijaya">LinkedIn</a> |
  <a href="https://github.com/indrikwijaya">GitHub</a> |
  <a href="https://www.cloudskillsboost.google/public_profiles/8fc13e1f-8d84-4a05-a784-0b3c7285e455">Google Cloud</a> |
  <a href="https://drive.google.com/drive/folders/1oSmNLq3gNf5fvhRNAUsiL_TiEuy_0Xeg">DataCamp</a>
  </p>
  
  <p align="left">
  A Math enthusiast with a strong passion in applying mathematics and statistics to tackle complex problems in biotechnology and life sciences.
  <br><br>
  Started my career by employing statistical techniques and machine learning algorithms to investigate the translational regulation in the mitochondria during brown fat differentiation.
  <br><br>
  Currently characterising the universal problem of aging and responses to drugs by developing and applying state-of-the-art bioinformatics and machine learning pipelines to multi-omics data.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
