title: <p align="center"> Indrik Wijaya </p>

logo: "/images/grad_photo.jpeg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://linkedin.com/in/indrik-wijaya">LinkedIn</a> |
  <a href="https://github.com/indrikwijaya">GitHub</a>
  </p>
  
  <p align="justify">
  A Math enthusiast with deep passion in applying mathematical and computational analysis to tackle complex problems such as aging and healthcare.
  <br><br>
  Started my career by employing statistical techniques and machine learning algorithms to investigate the translational regulation in the mitochondria during brown fat differentiation.
  <br><br>
  Currently focusing on tackling and universal problems of aging by exploiting multi-omics data through developing and applying state-of-the-art bioinformatics and machine learning pipelines.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
